name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_SECRET }}
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.generate-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@v4
        if: ${{ steps.release-please.outputs.pr }}
        with:
          ref: ${{ fromJson(steps.release-please.outputs.pr).headBranchName }}
          token: ${{ steps.generate-token.outputs.token }}
      - name: Generate mod changelog
        uses: sguest/release-please-factorio-changelog@v1
        if: ${{ steps.release-please.outputs.pr }}
        with:
          output-file: ${{ github.workspace }}/public/changelog.txt
      - name: Commit changelog
        if: ${{ steps.release-please.outputs.pr }}
        run: |
          git config --global user.name sguest-app-token-generator
          git config --global user.email sguest-app-token-generator@github.com
          git commit -am "chore: updated changelog.txt"
          git push
      - name: Checkout
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v3
      - name: Setup node
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/setup-node@v3
      - name: npm ci
        if: ${{ steps.release-please.outputs.release_created }}
        run: npm ci
      - name: npm run build
        if: ${{ steps.release-please.outputs.release_created }}
        run: npm run build
      - name: Install zip
        if: ${{ steps.release-please.outputs.release_created }}
        uses: montudor/action-zip@v0.1.1
      - name: Zip output
        if: ${{ steps.release-please.outputs.release_created }}
        run: zip -qq -r ../SimpleSeablock_${{ steps.release-please.outputs.major }}.${{ steps.release-please.outputs.minor }}.${{ steps.release-please.outputs.patch }}.zip SimpleSeablock
        working-directory: dist
      - name: Upload Release Asset
        if: ${{ steps.release-please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run:
          gh release upload ${{ steps.release-please.outputs.tag_name }} ${{ github.workspace }}/SimpleSeablock_${{ steps.release-please.outputs.major }}.${{ steps.release-please.outputs.minor }}.${{ steps.release-please.outputs.patch }}.zip
      - name: Publish to Mod Portal
        if: ${{ steps.release-please.outputs.release_created }}
        uses: mchangrh/factorio-mod-upload@v1
        with:
          mod-name: SimpleSeablock
        env:
          FACTORIO_MODS_TOKEN: ${{ secrets.FACTORIO_API_TOKEN }}
          FILENAME: ./SimpleSeablock_${{ steps.release-please.outputs.major }}.${{ steps.release-please.outputs.minor }}.${{ steps.release-please.outputs.patch }}.zip